version: "3"
services:
  nginx:
    build:
      dockerfile: Dockerfile.nginx
      context: .
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - server
  server:
    build:
      dockerfile: Dockerfile.node
      context: .
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - redis
  redis:
    container_name: redis-server
    image: redis
    ports:
      - "6379:6379"
