FROM node:10.15.3

WORKDIR /usr/src/app

COPY . .

RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.16.0-alpine
COPY --from=0 /usr/src/app/build /usr/share/nginx/html
COPY --from=0 /usr/src/app/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
