version: "3"
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    container_name: redis-server
    image: redis
    ports:
      - "6379:6379"
